image: gitlab-registry-production.govcms.amazee.io/govcms/govcms-ci:latest
services:
  - name: gitlab-registry-production.govcms.amazee.io/govcms/govcms-ci/dind:latest
    command: ["--tls=false"]

stages:
  - test
  - build

test:
  stage: test
  script:
    - docker build -f govcms-ci.Dockerfile -t govcms/govcms-ci:latest .
    - dgoss run -i govcms/govcms-ci:latest

build:
  stage: build
  script:
    - IMAGE_TAG=$([ $CI_COMMIT_BRANCH = 'master' ] && echo 'latest' || echo 'edge')
    - scripts/prepare
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f govcms-ci.Dockerfile -t $CI_REGISTRY/govcms/govcms-ci:${IMAGE_TAG} .
    - docker push $CI_REGISTRY/govcms/govcms-ci:${IMAGE_TAG}
    # Refresh internal docker:dind image.
    - docker pull docker:dind
    - docker tag docker:dind $CI_REGISTRY/govcms/govcms-ci/dind:latest
    - docker push $CI_REGISTRY/govcms/govcms-ci/dind:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
  only:
    - develop
    - master
