image: gitlab-registry-production.govcms.amazee.io/govcms/govcms-ci:latest
services:
  - name: gitlab-registry-production.govcms.amazee.io/govcms/govcms-ci/dind:latest
    command: ["--tls=false"]

stages:
  - build

build:
  stage: build
  script:
    - IMAGE_TAG=$([ $CI_COMMIT_BRANCH = 'master' ] && echo 'latest' || echo 'edge')
    - scripts/prepare
    - docker buildx create --name govcms-ci-amd-arm --platform linux/amd64,linux/arm64 tcp://localhost:2375
    - docker buildx ls
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx bake -f docker-compose.yml -f bake.hcl --builder govcms-ci-amd-arm --push
  variables:
    DOCKER_HOST: tcp://localhost:2375
  only:
    - develop
    - master
