image: gitlab-registry-production.govcms.amazee.io/govcms/govcms-ci:latest
services:
  - name: gitlab-registry-production.govcms.amazee.io/govcms/govcms-ci/dind:latest
    command: ["--tls=false"]

stages:
  - build

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "8.x"
      variables:
        IMAGE_TAG: "php8"
    - if: $CI_COMMIT_REF_NAME == "8.x-develop"
      variables:
        IMAGE_TAG: "php8-edge"
    - if: $CI_COMMIT_TAG != null
      variables:
        IMAGE_TAG: $CI_COMMIT_TAG

build:
  stage: build
  script:
    - BUILDX_VERSION=$(docker buildx version|grep 'github.com/docker/buildx') || true
    - scripts/prepare
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - |
      set -eux
      if [ ! -z "${BUILDX_VERSION}" ]; then
        docker buildx create --name govcms-ci-amd-arm --platform linux/amd64,linux/arm64
        docker buildx ls
        docker buildx bake -f docker-compose.yml -f bake.hcl --builder govcms-ci-amd-arm --push
      else
        docker build -f govcms-ci.Dockerfile -t $CI_REGISTRY/govcms/govcms-ci:${IMAGE_TAG} .
        docker push $CI_REGISTRY/govcms/govcms-ci:${IMAGE_TAG}
        docker pull docker:dind
        docker tag docker:dind $CI_REGISTRY/govcms/govcms-ci/dind:${IMAGE_TAG}
        docker push $CI_REGISTRY/govcms/govcms-ci/dind:${IMAGE_TAG}
      fi
  variables:
    DOCKER_HOST: tcp://localhost:2375
  only:
    - 8.x-develop
    - 8.x

build:creator-ee:
  stage: build
  script:
    - |
      set -eux
      CREATOR_EE_VERSION=${CREATOR_EE_VERSION:-v0.5.2}
      git clone -b ${CREATOR_EE_VERSION} https://github.com/ansible/creator-ee.git
      cd creator-ee
      docker build -t gitlab-registry-production.govcms.amazee.io/govcms/govcms-ci/ansible-creator-ee:${CREATOR_EE_VERSION} .
      docker push gitlab-registry-production.govcms.amazee.io/govcms/govcms-ci/ansible-creator-ee:${CREATOR_EE_VERSION}
  only:
    - develop
    - master
