version: '2.3'

x-environment:
  &default-environment
    DOCKERHOST: ${DOCKERHOST:-}

services:
  ci:
    build:
      context: .
      dockerfile: govcms-ci.Dockerfile
      args:
        GOVCMS_GITHUB_TOKEN: ${GOVCMS_GITHUB_TOKEN:-}
    image: govcms-ci
    environment:
      << : *default-environment
