version: 2
jobs:
  build:
    docker:
      - image: uselagoon/php-7.4-cli-drupal
        environment:
          GOSS_FILES_STRATEGY: cp
          DOCKER_VERSION: 20.10.14
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker
          command: |
            curl -L -o "/tmp/docker-${DOCKER_VERSION}.tgz" "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" \
            && tar -xz -C /tmp -f "/tmp/docker-${DOCKER_VERSION}.tgz" \
            && mv /tmp/docker/* /usr/bin \
            && docker --version
      - run:
          name: Install goss
          command: curl -fsSL https://goss.rocks/install | sh && goss --version
      - run: scmp_sys_resolver faccessat2
      # - run:
      #     name: Build image
      #     command: docker build -f govcms-ci.Dockerfile -t govcms/govcms-ci:latest .
      # - run:
      #     name: Test image
      #     command: dgoss run -i govcms/govcms-ci:latest
