---
fail-severity: normal
checks:
  file:
    - name: '[FILE] Illegal files'
      path: ./
      disallowed-pattern: '^(adminer|phpmyadmin|bigdump)?\.php$'
  yaml:
    - name: '[FILE] Validate install profile'
      file: core.extension.yml
      ignore-missing: true
      path: config/default
      values:
        - key: profile
          value: govcms
    - name: '[FILE] Disallowed permissions'
      pattern: user.role.*.yml
      exclude-pattern: user.role.govcms_site_administrator
      ignore-missing: true
      path: config/default
      values:
        - key: is_admin
          value: false
        - key: permissions
          is-list: true
          disallowed:
            - administer modules
            - administer permissions
            - administer site configuration
            - administer software updates
            - Administer the list of modules that can be managed by others
            - import configuration
            - use PHP for google analytics tracking visibility
    - name: '[FILE] Validate TFA config'
      file: tfa.settings.yml
      ignore-missing: true
      path: config/default
      values:
        - key: enabled
          value: 1
        - key: required_roles.authenticated
          value: authenticated
  drush-yaml:
    - name: '[DATABASE] Validate active install profile'
      command: 'config:get core.extension'
      config-name: core.extension
      values:
        - key: profile
          value: govcms
    - name: '[DATABASE] Validate active TFA'
      command: 'config:get tfa.settings'
      config-name: tfa.settings
      values:
        - key: enabled
          value: 1
        - key: required_roles.authenticated
          value: authenticated
  drupal-file-module:
    - name: '[FILE] Verify enabled modules'
      path: config/default
      required:
        - govcms_security
        - lagoon_logs
        - tfa
      disallowed:
        - dblog
        - module_permissions_ui
        - update
  drupal-db-module:
    - name: '[DATABASE] Active modules audit'
      required:
        - govcms_security
        - lagoon_logs
        - tfa
      disallowed:
        - dblog
        - module_permissions_ui
        - update
  drupal-db-permissions:
    - name: '[DATABASE] Disallowed permissions on active site'
      disallowed:
        - administer modules
        - administer permissions
        - administer site configuration
        - administer software updates
        - Administer the list of modules that can be managed by others
        - import configuration
        - use PHP for google analytics tracking visibility
      exclude-roles:
        - govcms_site_administrator
  yamllint:
    - name: '[FILE] Yaml lint platform files'
      files:
        - .lagoon.yml
        - docker-compose.yml
      ignore-missing: true
    - name: '[FILE] Yaml lint theme files'
      path: web/themes
      pattern: ".*.yml"
      exclude-pattern: node_modules
      ignore-missing: true
    - name: '[FILE] Yaml lint theme files (no web prefix)'
      path: themes
      pattern: ".*.yml"
      exclude-pattern: node_modules
      ignore-missing: true
  phpstan:
    - name: '[FILE] Banned PHP function list'
      binary: /govcms/vendor/bin/phpstan
      configuration: ./phpstan.neon
      paths:
        - themes
