#!/bin/bash

echo "[***] Build hook starting..."

IMAGE_TAG=edge

if [ "$CI_COMMIT_BRANCH" = "master" ]; then
  IMAGE_TAG=latest
fi

echo "[---] CI_REGISTRY: ${CI_REGISTRY}"
echo "[---] IMAGE_TAGE: ${IMAGE_TAG}"

if [ "$CI_COMMIT_BRANCH" = "develop" ]; then
  # Pin to the develop branch for scaffold-tooling.
  sed -i.bak -E "s#(\"govcms\/scaffold-tooling\":[[:space:]]*\").+(\")#\1dev-develop\2#g" composer.json
  echo "[---] Updated to govcms/scaffold-tooling:dev-develop"
fi

docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
docker build -f govcms-ci.Dockerfile -t $CI_REGISTRY/govcms/govcms-ci:${IMAGE_TAG}
docker build $CI_REGISTRY/govcms/govcms-ci:${IMAGE_TAG}
